#!/bin/sh

# This script can be used to prepare all build artifacts which are needed for a full product build without using
# the CI server (useful for development or testing or when the CI server is broken)
# This script is not being used by the CI server because it does it's own artifact handling.

MODULES="spellCli spellCore spellEd spellDocs spellFlash spellAndroid spelliOS"

for module in $MODULES; do

	mkdir -p build-artifacts/$module

	if [ ! -d ../$module ]; then
		echo "Missing ../$module directory"
		exit 1
	fi

	cd ../$module && make

	cp -ar ../$module/build/* build-artifacts/$module
done

