#!/bin/sh

VERSION=$(cat VERSION)
CUR_DIR=$(pwd)
DEST_DIR=generated/$VERSION

echo Building version $VERSION

if [ -d $DEST_DIR ]; then
	echo Destination dir $DEST_DIR already exists, purging directory!
	rm -Rf $DEST_DIR
fi

echo Preparing deploy directory $DEST_DIR...

mkdir -p $DEST_DIR/docs $DEST_DIR/spellCore $DEST_DIR/projects

echo Copying reference projects to generated directory...
cp -aR projects/* $DEST_DIR/projects

echo Building SpellEd...
cd modules/spellEd
make
cd $CUR_DIR
mkdir $DEST_DIR/spellEd
mkdir $DEST_DIR/spellEd/public
cp -aR modules/spellEd/build/output/* $DEST_DIR/spellEd/public
cp -aR modules/spellEd/src modules/spellEd/node_modules modules/spellEd/server $DEST_DIR/spellEd


echo Building SpellCore...
cp -aR modules/spellCore/* $DEST_DIR/spellCore
cd $DEST_DIR/spellCore
make
cd $CUR_DIR

echo Generating documentation...
cd $DEST_DIR/spellCore
make docs
cd $CUR_DIR
cp -aR $DEST_DIR/spellCore/docs/generated/* $DEST_DIR/docs

echo Stripping down export...
rm -Rf $DEST_DIR/spellCore/docs $DEST_DIR/spellCore/misc

