#!/bin/sh

VERSION=$1
if [ -z "$VERSION" ] ; then
    echo "Usage: $0 <VERSION>"
    exit
fi

CUR_DIR=$(pwd)
DEST_DIR=build

echo Building version $VERSION

echo Purging build directory...
rm -Rf $DEST_DIR/*


echo $VERSION >$DEST_DIR/VERSION

echo Preparing deploy directory $DEST_DIR...

mkdir -p $DEST_DIR/docs $DEST_DIR/spellCore $DEST_DIR/projects

echo Copying reference projects to generated directory...
cp -aR projects/battleblast $DEST_DIR/projects
cp -aR projects/box2dTest $DEST_DIR/projects
cp -aR projects/spellReferenceProject $DEST_DIR/projects

echo Building SpellEd...
cd modules/spellEd

#create app-configuration.js

cat >public/app-configuration.js <<EOF
//Provide a configuration for the SpellEd Editor
//CAUTION: This file will be overridden by the build process!
//see spellEngine/deploy script

Ext.ns("Ext.app");

Ext.app.CONFIGURATION = {
        "version" : "$VERSION",
	"storageVersion": 1,
        "name" : "SpellEd",
        "documentationServerURL": "http://docs.spelljs.com/$VERSION/"
};
EOF

make deploy
cd $CUR_DIR
mkdir $DEST_DIR/spellEd
mkdir $DEST_DIR/spellEd/public
cp -aR modules/spellEd/build/* $DEST_DIR/spellEd/public
cp -aR modules/spellEd/src modules/spellEd/server $DEST_DIR/spellEd

echo Copying node_modules...
cp -aR node_modules $DEST_DIR/

echo Building SpellCore...
cp -aR modules/spellCore/* $DEST_DIR/spellCore
cd $DEST_DIR/spellCore
make deploy
cd $CUR_DIR

echo Generating documentation...
cd $DEST_DIR/spellCore
make docs
cd $CUR_DIR
cp -aR $DEST_DIR/spellCore/docs/generated/* $DEST_DIR/docs

echo Stripping down export...
rm -Rf $DEST_DIR/spellCore/docs $DEST_DIR/spellCore/misc

#echo Reinitializing demo projects...
for PROJECT in $(ls "$DEST_DIR/projects"); do
  cd $DEST_DIR/projects/$PROJECT
  ../../spellCore/sappre init
  #remove assets directory
  rm -rf assets/
  cd $CUR_DIR
done
