#!/bin/sh

VERSION=$1
if [ -z "$VERSION" ] ; then
    echo "Usage: $0 <VERSION>"
    exit
fi

ARCHS="linux-ia32 linux-x64 osx-ia32 win-ia32"

CUR_DIR=$(pwd)
DEST_DIR=build

echo Building version $VERSION

echo Preparing build directory...
rm -Rf $DEST_DIR/*
mkdir -p $DEST_DIR/spellEd-cloud/public $DEST_DIR/spellEd-standalone $DEST_DIR/docs $DEST_DIR/spellCore

echo $VERSION >$DEST_DIR/VERSION

echo Building SpellEd...
cd modules/spellEd

#create app-configuration.js

cat >public/app-configuration.js <<EOF
//Provide a configuration for the SpellEd Editor
//CAUTION: This file will be overridden by the build process!
//see spellEngine/deploy script

Ext.ns("Ext.app");

Ext.app.CONFIGURATION = {
        "version" : "$VERSION",
	"storageVersion": 1,
        "name" : "SpellEd",
        "documentationServerURL": "http://docs.spelljs.com/$VERSION/"
};
EOF

make deploy
cd $CUR_DIR

echo Copying spellEd build...
cp -aR modules/spellEd/build/* $DEST_DIR/spellEd-cloud/public
cp -aR modules/spellEd/src modules/spellEd/server $DEST_DIR/spellEd-cloud

echo Copying node_modules...
cp -aR node_modules $DEST_DIR/spellEd-cloud

echo Building SpellCore...
cp -aR modules/spellCore/* $DEST_DIR/spellCore
cd $DEST_DIR/spellCore
make deploy
cd $CUR_DIR

echo Generating documentation...
cd $DEST_DIR/spellCore
make docs
cd $CUR_DIR
cp -aR $DEST_DIR/spellCore/docs/generated/* $DEST_DIR/docs

echo Stripping down export...
rm -Rf $DEST_DIR/spellCore/docs $DEST_DIR/spellCore/misc
