#!/bin/sh

VERSION=$(cat build/VERSION)
DEST_DIR=build
HOST=spelled.spielmeister.com

if [ ! -d $DEST_DIR ]; then
	echo Destination dir $DEST_DIR does not exists! Was the build already created?
	exit 0 
fi

#echo Creating directory on host $HOST
#ssh root@$HOST "mkdir /opt/spellEngine/$VERSION"

ssh root@$HOST "cp -aRL /opt/spellEngine/latest/ /opt/spellEngine/$VERSION"

echo Deploying version $VERSION on host $HOST
rsync -avzC --delete $DEST_DIR/* root@$HOST:/opt/spellEngine/$VERSION

echo

echo Running spellctl_set_latest_version $VERSION on $HOST
ssh root@$HOST "nohup /opt/spellCloud/bin/spellctl_set_latest_version $VERSION </dev/null >>/var/log/spellCloud.log 2>&1 &"
