#!/bin/sh

DIRNAME=$(cd `dirname $0` && pwd)

if [ $# -lt 2 ]; then
	echo Usage: $0 DEPLOY_HOST SPELLCLOUD_PACKAGE
	exit 1
fi

DEPLOY_HOST=$1
SPELLCLOUD_PACKAGE=$DIRNAME"/"$2

if [ -z "$SPELLCLOUD_PACKAGE" ] || [ ! -f $SPELLCLOUD_PACKAGE  ]; then
	echo No or invalid SPELLCLOUD_PACKAGE specified
	exit 1
fi

VERSION=$(cat VERSION)
SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_rsa_buildbot"
TMP_DIR=/tmp/$$

#fix permissions for private key
chmod 600 id_rsa_buildbot

if [ -z "$VERSION" ]; then
	echo Could not read VERSION
	exit 1
fi

mkdir $TMP_DIR && cd $TMP_DIR && tar -xvzf $SPELLCLOUD_PACKAGE && cd $DIRNAME

echo "Copy old latest version to current version..."

$SSH root@$DEPLOY_HOST "cp -aRL /opt/spellEngine/latest/ /opt/spellEngine/$VERSION"

echo "Rsyncing new version..."

rsync -avzC --delete -e "$SSH" \
$TMP_DIR/ \
root@$DEPLOY_HOST:/opt/spellEngine/$VERSION

echo "Running spellctl_set_latest_version..."

$SSH root@$DEPLOY_HOST "nohup /opt/spellCloud/bin/spellctl_set_latest_version $VERSION </dev/null >>/var/log/spellCloud.log 2>&1 &"

rm -rf $TMP_DIR
