#!/bin/sh

VERSION=$(cat build/VERSION)
DEST_DIR=build
HOST=spelled.spielmeister.com

if [ ! -d $DEST_DIR ]; then
	echo Destination dir $DEST_DIR does not exists! Was the build already created?
	exit 0 
fi

echo Creating directory on host $HOST
ssh root@$HOST "mkdir /opt/spellEngine/$VERSION"

echo Deploying version $VERSION on host $HOST
rsync -avzC --delete $DEST_DIR/* root@$HOST:/opt/spellEngine/$VERSION

echo Symlinking "latest" to version $VERSION
ssh root@$HOST "rm /opt/spellEngine/latest && ln -sf /opt/spellEngine/$VERSION /opt/spellEngine/latest"

echo Syncing user and tools...
rsync -vz live-server/* build/VERSION root@$HOST:/root

echo Recreating vhosts and restarting apache...
ssh root@$HOST "cd /root && ./generate_vhosts_and_users"

echo Starting servers...
ssh root@$HOST "cd /root && ./start_servers"

