#!/bin/sh

if [ -z "$DEPLOY_HOST" ]; then
	echo No DEPLOY_HOST specified
	exit 1
fi

if [ -z "$BUILD_DIR" ] || [ ! -d $BUILD_DIR  ]; then
	echo No or invalid BUILD_DIR specified
	exit 1
fi

VERSION=$(cat VERSION)
if [ -z "$VERSION" ]; then
	echo Could not read VERSION
	exit 1
fi

SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_rsa_buildbot"
FILES="spelljs-desktop-$VERSION-linux-x64.zip spelljs-desktop-$VERSION-win-ia32.zip spelljs-desktop-$VERSION-osx-ia32.zip"

#fix permissions for private key
chmod 600 id_rsa_buildbot

for file in $FILES; do
	if [ ! -f $BUILD_DIR/$file ]; then
		echo could not find file $file
		exit 1
	fi

	rsync -avzC --delete -e "$SSH" \
$BUILD_DIR/$file \
root@$DEPLOY_HOST:/var/cdn/

done

