#!/bin/sh

GIT_REVISION=$1
if [ -z "$GIT_REVISION" ] ; then
    echo "Usage: $0 <GIT_REVISION>"
    exit
fi

# reset all changes made to this checkout (including submodules)
git reset --hard
git submodule foreach 'git reset --hard'

# check out the specified revision
git fetch origin
git checkout $GIT_REVISION

CHECK_GIT_REVISION=$(git rev-parse --verify HEAD)

if [ "$GIT_REVISION" != "$CHECK_GIT_REVISION" ]; then
	echo Could not checkout $GIT_REVISION
	exit 1
fi

git submodule init
git submodule update
