#!/bin/sh

GIT_REVISION=$1
if [ -z "$GIT_REVISION" ] ; then
    echo "Usage: $0 <GIT_REVISION>"
    exit
fi

git fetch origin
git checkout $GIT_REVISION
git reset --hard

git submodule init
git submodule update
