#!/bin/sh

WORKSPACE=$1

if [ ! -d "$WORKSPACE" ] ; then
	echo "Usage: $0 WORKSPACE_DIRECTORY"
	exit 1
fi


for PROJECT in `ls -1 $WORKSPACE`
do
	if [ -f "$WORKSPACE/$PROJECT/project.json" ]
	then
		modules/spellCore/spellcli init -p $WORKSPACE/$PROJECT
	fi
done

