#!/bin/sh

VERSION=$(cat VERSION)
VERSION="SpellJS-$VERSION"

#tag the current version
git tag -a "$VERSION" -m "$VERSION release"
git push origin --tags

git submodule foreach "git tag -a $VERSION -m \"$VERSION release\""
git submodule foreach "git push origin --tags"

#copy the current version to LAST_RELEASED_VERSION
cat VERSION >LAST_RELEASED_VERSION
git add LAST_RELEASED_VERSION 
git commit LAST_RELEASED_VERSION -m "updated LAST_VERSION file"
