#!/bin/sh

VERSION=$1

if [ -z "$VERSION" ] ; then
	echo "Usage: $0 <VERSION>"
	exit 1
fi


echo Updating version in spellProduct repository to $VERSION
git reset --hard
git checkout master
git reset --hard
git pull

# change version in VERSION file
echo $VERSION >VERSION
git add VERSION
git commit -m "Changed version to $VERSION" VERSION

# change version of MSI generator
perl -pi -e "s/Version = \"[^\"]*\"/Version = \"$VERSION\"/g" resources/win/spellProduct.wxs 
git add resources/win/spellProduct.wxs
git commit -m "Changed version $VERSION for MSI package generation" resources/win/spellProduct.wxs

git push origin master

#setting version and build of spelled
echo Updating version in spellEd to $VERSION

cd ../spellEd

git reset --hard
git checkout master
git reset --hard
git pull

perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" public/app/Configuration.js
perl -pi -e "s/\"version\"(\s*):(\s*)\"[^\"]*\",/\"version\"\1:\2\"$VERSION\",/g" nw-package/package.json 
perl -pi -e "s/\"version\"(\s*):(\s*)\"[^\"]*\",/\"version\"\1:\2\"$VERSION\",/g" nw-debug-package/package.json 

git add public/app/Configuration.js nw-package/package.json nw-debug-package/package.json
git commit -m "Changed version to $VERSION" public/app/Configuration.js nw-package/package.json nw-debug-package/package.json
git push origin master

cd spellProduct

echo Updating version in spellCore to $VERSION

#setting version of spellcli
cd ../spellCli

git reset --hard
git checkout master
git reset --hard
git pull

perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" src/spell/BuildInfo.js 

git add src/spell/BuildInfo.js 
git commit -m "Changed version to $VERSION" src/spell/BuildInfo.js 
git push origin master

