#!/bin/sh

BUILDNUMBER=$1
BUILDTIMESTAMP=$2

if [ -z "$BUILDNUMBER" ] ; then
	echo "Usage: $0 BUILDNUMBER BUILDTIMESTAMP"
	exit 1
fi

if [ -z "$BUILDTIMESTAMP" ] ; then
	echo "Usage: $0 BUILDNUMBER BUILDTIMESTAMP"
	exit 1
fi

#setting version and build of spelled
perl -pi -e "s/buildNumber(\s*):(\s*)\'[^\']*\',/build\1:\2\'$BUILDNUMBER\',/g" modules/spellEd/public/app/Configuration.js
perl -pi -e "s/buildTimeStamp(\s*):(\s*)\'[^\']*\',/buildtime\1:\2\'$BUILDTIMESTAMP\',/g" modules/spellEd/public/app/Configuration.js

#setting version of spellcli
perl -pi -e "s/buildNumber(\s*):(\s*)\'[^\']*\',/build\1:\2\'$BUILDNUMBER\',/g" modules/spellCore/src/spell/shared/Configuration.js
perl -pi -e "s/buildTimeStamp(\s*):(\s*)\'[^\']*\',/buildtime\1:\2\'$BUILDTIMESTAMP\',/g" modules/spellCore/src/spell/shared/Configuration.js

