#!/bin/sh

VERSION=$1
BUILD=$2
BUILDTIME=$3

if [ -z "$VERSION" ] ; then
	echo "Usage: $0 <VERSION> [<BUILD>] [<BUILDTIME>]"
	exit 1
fi

#setting version and build of spelled
perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" modules/spellEd/public/app/Configuration.js
perl -pi -e "s/buildNumber(\s*):(\s*)\'[^\']*\',/build\1:\2\'$BUILD\',/g" modules/spellEd/public/app/Configuration.js
perl -pi -e "s/buildTimeStamp(\s*):(\s*)\'[^\']*\',/buildtime\1:\2\'$BUILDTIME\',/g" modules/spellEd/public/app/Configuration.js

#setting version of spellcli
perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" modules/spellCore/src/spell/shared/Configuration.js
perl -pi -e "s/buildNumber(\s*):(\s*)\'[^\']*\',/build\1:\2\'$BUILD\',/g" modules/spellCore/src/spell/shared/Configuration.js
perl -pi -e "s/buildTimeStamp(\s*):(\s*)\'[^\']*\',/buildtime\1:\2\'$BUILDTIME\',/g" modules/spellCore/src/spell/shared/Configuration.js

