#!/bin/sh

VERSION=$1

if [ -z "$VERSION" ] ; then
	echo "Usage: $0 <VERSION>"
	exit 1
fi


echo Updating version in spellEngine repository to $VERSION
git checkout master
git reset --hard
git pull

echo $VERSION >VERSION
git add VERSION
git commit -m "Changed version to $VERSION"
git push origin master

#setting version and build of spelled
echo Updating version in spellEd to $VERSION

cd modules/spellEd

git checkout master
git reset --hard
git pull

perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" public/app/Configuration.js
perl -pi -e "s/\"version\"(\s*):(\s*)\"[^\"]*\",/\"version\"\1:\2\"$VERSION\",/g" nw-package/package.json 
perl -pi -e "s/\"version\"(\s*):(\s*)\"[^\"]*\",/\"version\"\1:\2\"$VERSION\",/g" nw-debug-package/package.json 

git add public/app/Configuration.js nw-package/package.json nw-debug-package/package.json
git commit -m "Changed version to $VERSION"
git push origin master

cd ../..

echo Updating version in spellCore to $VERSION

#setting version of spellcli
cd modules/spellCore

git checkout master
git reset --hard
git pull

perl -pi -e "s/version(\s*):(\s*)\'[^\']*\',/version\1:\2\'$VERSION\',/g" src/spell/shared/Configuration.js

git add src/spell/shared/Configuration.js
git commit -m "Changed version to $VERSION"
git push origin master

cd ../..

