#!/usr/bin/env node

var connect		= require('connect'),
    http		= require('http'),
    os			= require('os'),
    networkInterfaces	= os.networkInterfaces(),
    ipAddress		= '127.0.0.1' 



for ( var dev in networkInterfaces ) {
	networkInterfaces[ dev ].forEach( function( details ) {
		if ( details.family == 'IPv4' && details.internal === false ) {
			ipAddress = details.address
		}
	});
}

var port = 1234

var app = connect()
	 .use( connect.logger( 'dev' ) )
	 .use( connect.static( 'public' ) )

http.Server( app ).listen( port )

console.log( 'URL for CoocoonJS launcher: http://' + ipAddress + ':' + port + '/index.html' )

