#!/bin/sh

VERSION=$(cat build/VERSION)

cd modules/spellEd
git add public/app-configuration.js
git commit -m "Version $VERSION release"
git push

cd ../..

git add VERSION
git add modules/*
git commit -m "Version $VERSION release"
git push

git tag -a "$VERSION" -m "Version $VERSION release"              
git push --tags

