#!/bin/sh

GIT_REVISION=$1
if [ -z "$GIT_REVISION" ] ; then
    echo "Usage: $0 <GIT_REVISION>"
    exit
fi


VERSION=$(cat VERSION)
VERSION="SpellJS-$VERSION"

#tag the current version
git tag -a "$VERSION" -m "$VERSION release" $GIT_REVISION
git push origin --tags
