#!/bin/sh

DEPLOY_HOST="web.spielmeister.com"
SSH="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

FILE=$(ls build/spelljs-*)
    
if [ ! -f $FILE ]; then
	echo Could not find file $FILE
	exit 1
fi

echo Copying $FILE
    
rsync -vzC -e "$SSH" \
$FILE \
root@$DEPLOY_HOST:/srv/cdn/prerelease

