#!/bin/sh

PATH=$PATH:"/cygdrive/c/Program Files (x86)/WiX Toolset v3.7/bin"
DIRNAME=$(cd `dirname $0` && pwd)

if [ $# -lt 2 ]; then
	echo Usage $0 PATH_TO_DIRECTORY/ OUTPUT.msi
	exit 1
fi

IN_DIR_CYGWIN=$(cd $1 && pwd)
IN_DIR=$(cygpath.exe -w $IN_DIR_CYGWIN)

OUTFILE_CYGWIN=$(cd `dirname $2` && pwd)/$(basename $2)
OUTFILE=$(cygpath.exe -w $OUTFILE_CYGWIN)

OUTDIR_CYGWIN=$(cd `dirname $2` && pwd)

PRODUCT_WXS_CYGWIN=$DIRNAME/SpellProduct.wxs
PRODUCT_WXS=$(cygpath.exe -w $PRODUCT_WXS_CYGWIN)

TMP_DIR_CYGWIN=/tmp/$$
TMP_DIR=$(cygpath.exe -w $TMP_DIR_CYGWIN)

TMP_WXS_CYGWIN=$TMP_DIR/files.wxs
TMP_WXS=$(cygpath.exe -w $TMP_WXS_CYGWIN)

mkdir $TMP_DIR_CYGWIN
mkdir $TMP_DIR_CYGWIN/wixobj

echo Packaging all files from $IN_DIR into MSI package $OUTFILE using TMP_DIR $TMP_DIR and WXS file $PRODUCT_WXS

heat.exe dir $IN_DIR -gg -dr INSTALLDIR -cg TheProduct -template fragment -out $TMP_WXS &&\
candle.exe $PRODUCT_WXS $TMP_WXS -o $TMP_DIR\\wixobj\\ &&\
light.exe $TMP_DIR\\wixobj\\* -b $IN_DIR\\ -out $OUTFILE

rm -rf $TMP_DIR_CYGWIN
rm -f $OUTDIR_CYGWIN/*wixpdb

