#!/bin/sh

PATH=$PATH:"/cygdrive/c/Program Files (x86)/WiX Toolset v3.7/bin"
DIRNAME=$(cd `dirname $0` && pwd)

heat dir . -gg -cg SpellProduct -template fragment -out files.wxs

candle.exe $DIRNAME/SpellProduct.wxs files.wxs
light.exe SpellProduct.wixobj files.wixobj -out test.msi

# remove temp files
rm SpellProduct.wixobj files.wxs files.wixobj
