#!/bin/sh

if [ -z "$1" ]; then
	echo Usage: $0 PNGFILE.png
	exit 1
fi

INPUT=$1

ICON_SIZES="16 32 48 64 128"
ICONS=""

for size in $ICON_SIZES; do
	FILENAME=icon_$size\x$size.png
	
	convert -colors 256 -resize $sizex$size $INPUT \
		$FILENAME
	ICONS="$ICONS $FILENAME "
done

icotool -c -o icon.ico $ICONS
rm $ICONS
