#!/bin/sh

if [ -z "$1" ]; then
	echo Usage: $0 PNGFILE.png
	exit 1
fi

INPUT=$1

ICON_SIZES="16 32 48 64 128"

for size in $ICON_SIZES; do
	convert -colors 256 -resize $sizex$size $INPUT \
		icon_$size\x$size.ico
done
