#!/usr/bin/perl

use strict;

&kill_server();

my $p = 3000;
open(FILE, "<alpha-test-users") || die $!;
while (<FILE>) {
	chomp; next unless $_;
	@_ = split /\s/;
	push @_, ++$p;
	&start_server
}

sub kill_server {
	system("killall -9 node");
}

sub start_server {
	my ($vhost, $user, $pass, $email, $port_number) = @_;

	my $cmd;

	#start spelled server
	$cmd = "cd /opt/spellEngine/latest/spellEd && ./server start-server -p " . $port_number . " -b ". $port_number ."0 -r ../../../../home/". $vhost ." 2>&1 >/dev/null &";

	print "# starting spelled server for " . $vhost . "...\n";
	print $cmd . "\n";
	system($cmd);

	#start build server
	$cmd = "cd /opt/spellEngine/latest/spellCore && ./sappre start-server -p " . $port_number . "0 -r ../../../../home/". $vhost ." 2>&1 >/dev/null &";
	
	print "# starting build server for " . $vhost . "...\n";
	print $cmd . "\n";
	system($cmd);


}

